/*
 * BaseObject.h
 *
 *  Created on: 20 Sep 2019
 *      Author: hemant
 */

#ifndef SRC_SIMPLEZIGBEE_OBJECT_BASEOBJECT_H_
#define SRC_SIMPLEZIGBEE_OBJECT_BASEOBJECT_H_
#include <vector>
#include "stdint.h"
namespace SimpleZigbeeName {

//System Sub Commands
enum SysCommandsEnum : uint8_t
{
	SYS_RESET_REQ = 0x00,
	SYS_PING,
	SYS_VERSION,
	SYS_SET_EXTADDR,
	SYS_GET_EXTADDR,
	SYS_RAM_READ,
	SYS_RAM_WRITE,
	SYS_OSAL_NV_ITEM_INIT,
	SYS_OSAL_NV_READ,
	SYS_OSAL_NV_WRITE = 0x09,
	SYS_OSAL_START_TIMER = 0x0A,
	SYS_OSAL_STOP_TIMER,
	SYS_RANDOM,
	SYS_ADC_READ,
	SYS_GPIO,
	SYS_STACK_TUNE = 0x0F,
	SYS_SET_TIME,
	SYS_GET_TIME,
	SYS_OSAL_NV_DELETE = 0x12,
	SYS_OSAL_NV_LENGTH,
	SYS_SET_TX_POWER = 0x14,
	SYS_ZDIAGS_INIT_STATS = 0x17,
	SYS_ZDIAGS_CLEAR_STATS,
	SYS_ZDIAGS_GET_STATS,
	SYS_ZDIAGS_RESTORE_STATS_NV = 0x1A,
	SYS_ZDIAGS_SAVE_STATS_TO_NV,
	SYS_NV_CREATE = 0X30,
	SYS_NV_DELETE,
	SYS_NV_LENGTH,
	SYS_NV_READ = 0X33,
	SYS_NV_WRITE= 0X34,
	SYS_NV_UPDATE = 0X35,
	SYS_NV_COMPACT
};


enum MtUtilCommandsEnum : uint8_t
{
	MT_UTIL_GET_DEVICE_INFO = 0x00,
	MT_UTIL_GET_NV_INFO,
	MT_UTIL_SET_PANID,
	MT_UTIL_SET_CHANNELS,
	MT_UTIL_SET_SECLEVEL,
	MT_UTIL_SET_PRECFGKEY,
	MT_UTIL_CALLBACK_SUB_CMD,
	MT_UTIL_KEY_EVENT,
	MT_UTIL_TIME_ALIVE =0x09,
	MT_UTIL_LED_CONTROL,
	MT_UTIL_LOOPBACK = 0x10,
	MT_UTIL_DATA_REQ,
	MT_UTIL_SRC_MATCH_ENABLE = 0x20,
	MT_UTIL_SRC_MATCH_ADD_ENTRY,
	MT_UTIL_SRC_MATCH_DEL_ENTRY,
	MT_UTIL_SRC_MATCH_CHECK_SRC_ADDR,
	MT_UTIL_SRC_MATCH_ACK_ALL_PENDING,
	MT_UTIL_SRC_MATCH_CHECK_ALL_PENDI,
	MT_UTIL_ADDRMGR_EXT_ADDR_LOOKUP = 0x40,
	MT_UTIL_ADDRMGR_NWK_ADDR_LOOKUP,
	MT_UTIL_APSME_LINK_KEY_DATA_GET = 0x44,
	MT_UTIL_APSME_LINK_KEY_NV_ID_GET,
	MT_UTIL_APSME_REQUEST_KEY_CMD = 0x4B
};

//Lets place important indexes first
const uint8_t CMD0_INDEX = 2;
const uint8_t CMD1_INDEX = 3;
const uint8_t DATA_INDEX = 4;

//const uint8_t STATUS_SUCCESS = 0;
//const uint8_t STATUS_FAIL	 = 1;

enum DeviceStatusEnum : uint8_t
{
	STATUS_SUCCESS = 0,
	STATUS_FAIL
};

enum DeviceTypeEnum : uint8_t
{
	DEVICE_CORDINATOR = 0,
	DEVICE_ROUTER,
	DEVICE_ENDPOINT
};

class BaseObject
{
public:
	BaseObject() = default;
	virtual ~BaseObject() = default;
	//BaseObject(std::vector<uint8_t>&);
	virtual uint16_t getCommand() = 0;
	virtual bool create(const std::vector<uint8_t>&) = 0;
	virtual void print() = 0;
};

}; /* namespace SimpleZigbeeName */

#endif /* SRC_SIMPLEZIGBEE_OBJECT_BASEOBJECT_H_ */
